routes:
  WorkersTotal:
    matchers:
      title: "status"
      env: "production"
      source: "gearman-load-logger"
    output:
      type: "alerts"
      series: "WorkersTotal"
      stat_type: "gauge"
      value_field: "value"
      dimensions: ["function"]
  WorkersAvailable:
    matchers:
      title: "status"
      env: "production"
      source: "gearman-load-logger"
    output:
      type: "alerts"
      series: "WorkersAvailable"
      stat_type: "gauge"
      value_field: "available_workers"
      dimensions: ["function"]
