routes:
  WorkersTotal:
    matchers:
      title: ["total_workers"]
      deploy_env: ["production"]
    output:
      type: "alerts"
      series: "WorkersTotal"
      stat_type: "gauge"
      value_field: "value"
      dimensions: ["function"]
  WorkersAvailable:
    matchers:
      title: ["total_workers"]
      deploy_env: ["production"]
    output:
      type: "alerts"
      series: "WorkersAvailable"
      stat_type: "gauge"
      value_field: "available_workers"
      dimensions: ["function"]
